version: '3.9'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

  minio:
    image: minio/minio
    ports:
      - "9090:9090"
      - "9000:9000"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: rootuser
      MINIO_ROOT_PASSWORD: rootpassword
    command: server /data --console-address ":9090"
    healthcheck:
      test: curl -f http://localhost:9000/minio/health/ready
      interval: 2s
      retries: 3
      start_period: 10s
      timeout: 1s

  minio-initializer:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: rootuser
      MINIO_ROOT_PASSWORD: rootpassword
      MINIO_BUCKET_NAME: it-blog-images
    entrypoint: >
      /bin/sh -c "
       mc alias set minio_alias http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD;
       if mc stat minio_alias/$$MINIO_BUCKET_NAME > /dev/null 2>&1; then
         echo 'Bucket $$MINIO_BUCKET_NAME already exists.';
       else
         mc mb minio_alias/$$MINIO_BUCKET_NAME;
         mc anonymous set download minio_alias/$$MINIO_BUCKET_NAME
       fi;
       exit 0;
      "

volumes:
  mongodb_data: { }
  minio_data: { }
