spring:
  servlet:
    multipart:
      max-file-size: 5MB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: itBlog
      username: rootuser
      password: rootpassword
      authentication-database: admin
    redis:
      host: localhost
      port: 6379

images:
  s3Endpoint: http://localhost:9000
  bucketName: it-blog-images
  accessKey: rootuser
  secretKey: rootpassword

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG