spring:
  servlet:
    multipart:
      max-file-size: 5MB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: itBlog
      username: rootuser
      password: rootpassword
      authentication-database: admin
minio:
  endpoint: http://localhost:9000
  bucketName: bucket
