spring:
  servlet:
    multipart:
      max-file-size: 5MB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: itBlog
      username: rootuser
      password: rootpassword
      authentication-database: admin

images:
  s3Endpoint: http://localhost:9000
  bucketName: it-blog-images
  accessKey: rootuser
  secretKey: rootpassword